import './globals.css'
import type { Metadata } from 'next'
import { Inter } from "next/font/google"
import Navbar from "./components/global/Navbar"
import Footer from "./components/global/Footer"
import UTM from "./components/global/UTM"
import PostgresTest from "./components/global/PostgresTest"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Branch off development',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-zinc-900 text-white`}>
        <Navbar />
        <UTM />
        <PostgresTest />
        {children}
        <Footer />
      </body>
    </html>
  )
}
